addSbtPlugin("org.jetbrains.scala" % "sbt-ide-settings" % "1.1.2")
addSbtPlugin("com.eed3si9n" % "sbt-buildinfo"  % "0.11.0")
addSbtPlugin("com.github.sbt" %% "sbt-git" % "2.0.0")
addSbtPlugin("com.github.sbt" %% "sbt-native-packager" % "1.10.0")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "1.1.0")
