name: HumiditySensorApp

on:
  push:
    tags:
      - "[0-9].[0-99].[0-99]"
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Run tests
        run: sbt test
      - name: Build JAR
        run: sbt assembly
      - name: Build Docker image
        run: docker build -t my-docker-image .
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Tag Docker image
        run: docker tag humidity-sensor-app ${{ secrets.DOCKER_USERNAME }}/humidity-sensor-app:latest
      - name: Publish Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-docker-image:latest
