name: HumiditySensorApp

on:
  push:
    branches: [ "main" ]
    tags:
      - "[0-9].[0-99].[0-99]"
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Run tests
        run: sbt test
      - name: Build JAR
        run: sbt assembly
      - name: Build Docker image
        run: sbt docker:publishLocal
      - name: Publish Docker image
        run: |
          IMAGE_TAG=${GITHUB_REF#refs/tags/}
          sbt docker:publish
